stages:
  raw_dataset_creation:
    cmd: python src/data/make_raw_data.py --config=params.yaml
    deps:
    - src/data/make_raw_data.py
    - data/external/train.csv
    outs:
    - data/raw/train.csv
  
  feature_engineering:
    cmd: python src/data/features_engineering.py --config=params.yaml
    deps:
    - src/data/features_engineering.py
    - data/raw/train.csv
    outs:
    - data/interim/train_interim.csv
  
  split_data:
    cmd: python src/data/split_dataset.py --config=params.yaml
    deps:
    - src/data/split_dataset.py
    - data/interim/train_interim.csv
    outs:
    - data/processed/churn_train.csv
    - data/processed/churn_test.csv

  model_train:
    cmd: python src/models/train_models.py --config=params.yaml
    deps:
    - data/processed/churn_train.csv
    - data/processed/churn_test.csv
    - src/models/train_models.py
    params:
    - random_forest.max_depth
    - random_forest.n_estimators

  log_production_model:
    cmd: python src/models/prod_model_selection.py --config=params.yaml
    deps:
    - src/models/prod_model_selection.py
    params:
    - random_forest.max_depth
    - random_forest.n_estimators
    outs:
    - models/model.joblib