external_data_config:
  external_data_csv: data/external/train.csv

raw_data_config: 
  raw_data_csv: data/raw/train.csv
  model_var: [
    "churn",
    "international_plan",
    "voice_mail_plan",
    "number_vmail_messages",
    "total_day_minutes",
    "total_day_calls",
    "total_day_charge",
    "total_eve_minutes",
    "total_eve_calls",
    "total_eve_charge",
    "total_night_minutes",
    "total_night_calls",
    "total_night_charge",
    "total_intl_minutes",
    "total_intl_calls",
    "total_intl_charge",
    "number_customer_service_calls"
]

interim_data_config:
  target: churn
  interim_data_csv: data/interim/train_interim.csv
  train_test_split_ratio: 0.2
  random_state: 111

processed_data_config:
  train_data_csv: data/processed/churn_train.csv
  test_data_csv:  data/processed/churn_test.csv

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: churn_experimentation
  run_name: train
  model_names: 
  - knn
  - decision_tree
  - logistic_regression
  - random_forest
  remote_server_uri: http://localhost:1234
 
random_forest: 
  max_depth: 10
  n_estimators: 100

metrics:
  average_method: weighted

model_dir: models/model.joblib

model_webapp_dir: ../../models/model.joblib

model_monitor:
  target_col_name: target
  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html